import { Inter } from "next/font/google";
import "./globals.css";
import HomepageComponent from "@/Components/HomepageComponent";
import NavbarComponent from "@/Components/NavbarComponent";
import TypeMovieComponent from "@/Components/TypeMovieComponent";
import CardMovieComponent from "@/Components/CardMovieComponent";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <NavbarComponent/>
        {children}
        
        </body>
    </html>
  );
}
